### ISSUE TITLE
Compatibility between EM Manned-BAYES and Traffic Density Database

### ISSUE THREAD

**Issue by rag315** [mit-ll/traffic-density-database#2]
Using MATLAB Version 2020b. All relevant toolboxes have been installed. 

My understanding of the Air Traffic Density Database is that you can provide it with a track and see the air traffic density along the aircraft track, and the EM Manned-BAYES repository can be used to generate aircraft tracks. Intuitively, I tried to analyze the traffic along the tracks that Manned-BAYES generated. However, the track output of Manned-BAYES does not appear to match the track input of the Air Traffic Density Database. 

I was able to generate tracks using Manned-BAYES, and the column outputs are: 
time (s), x (ft), y (ft), z (ft)

However, looking at the simple track example for the Air Traffic Density Database, the column inputs should be: 
time, latitude, longitude, altitude, true air speed (tas)

Are there plans to make these two repositories compatible in the future?

**Comment by aweinert-MIT** [comment]
All the models in [`em-model-manned-bayes`](https://github.com/Airspace-Encounter-Models/em-model-manned-bayes) are general, statistical models of crewed aircraft behavior. As noted in the  [`em-model-manned-bayes`](https://github.com/Airspace-Encounter-Models/em-model-manned-bayes) README:

> Do the models account for traffic density?
> No, the encounter models do not provide information on the density of manned aircraft behavior per unit time. The encounter model initial network aggregates all the observations across the training time window. It does not provide guidance on the density of aircraft.

Because these are generalized models, tracks are generated using a relative local Cartesian coordinate system with units of seconds and feet. The model itself has no latitude, longitude, or elevation (terrain) information. 

If you're interested in transforming sampled tracks from a local Cartesian  to a geodetic coordinate system, please review [`placeTrack`](https://github.com/Airspace-Encounter-Models/em-pairing-geospatial/blob/c1d4941bdd14714b1aaf7961ac9ab548221e4d5e/placeTrack.m) from the [`em-pairing-geospatial`](https://github.com/Airspace-Encounter-Models/em-pairing-geospatial) repository. This function currently inputs a track with a local Cartesian coordinate system and transforms it to latitude / longitude / altitude based on the reference coordinate `(lat0,lon0)`. You can estimate air speed from the position coordinates and then use the transformed track with `traffic-density-database`. 

Additionally, we're looking into moving `placeTrack` into `em-model-manned-bayes` as part of a larger update to `em-pairing-geospatial` later this year.
